version: 2

setup: &setup
  docker:
    - image: docker:17.05.0-ce-git
  working_directory: ~/tutorials

jobs:

  build:
    <<: *setup
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and save Docker image
          command: |
            DOCKER_IMAGE=nsidc/tutorials

            if [[ "${CIRCLE_TAG}" ]]; then
              export TAG=${CIRCLE_TAG}
            elif [[ "${CIRCLE_BRANCH}" = "master" ]]; then
              export TAG="latest"
            else
              export TAG=$CIRCLE_BRANCH
            fi
            echo "TAG: ${TAG}"

            docker build -t ${DOCKER_IMAGE}:${TAG}

            mkdir -p build
            docker save -o build/saved-docker-image.tar ${DOCKER_IMAGE}:${TAG}
            echo "${DOCKER_IMAGE}:${TAG}" > build/docker-image-name.txt
      - persist_to_workspace:
          root: ~/tutorials
          paths:
            - build

  deploy:
    <<: *setup
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/tutorials
      - deploy:
          name: Publish Docker image
          command: |
            docker load < build/saved-docker-image.tar
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push $(cat build/docker-image-name.txt)

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*$/

      - deploy:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^.*$/
            branches:
              only: /^master$/

